version: '3.1'
services:
    coredns:
        image: coredns:1.8.4
        container_name: coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './config/corefile:/etc/coredns/corefile'
            - './config/files/:/etc/coredns/plugin/'
        network_mode: host

